# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PennApps2015' do

pod "PubNub", "~> 4.0"

end

target 'PennApps2015Tests' do

end

